### ISSUE TITLE
一个不重要的小问题，HelloWorld那个章节的README有个笔误的地方

### ISSUE THREAD

**Issue by Daydaydaydaydream** [muyuuuu/CUDA#1]
“linux 操作系如”-->“linux 操作系统”

best wish  ：）

**Comment by muyuuuu** [comment]
> “linux 操作系如”-->“linux 操作系统”
> 
> best wish ：）

回家就改。话说能看懂吗，我感觉我写的好跳跃.......

**Comment by Daydaydaydaydream** [comment]
> > “linux 操作系如”-->“linux 操作系统”
> > best wish ：）
> 
> 回家就改。话说能看懂吗，我感觉我写的好跳跃.......

目前是跟着demo在做，对我来说算很友好了
